name: Veracode_Advanced
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Empacotamento dos arquivos
        uses: thedoctor0/zip-release@master
        with:
          filename: 'veracode.zip'
          path: .
      - name: Publicando Artefato
        uses: actions/upload-artifact@v2
        with:
          name: pacoteVeracode
          path: veracode.zip
  
  Veracode_SCA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDY0MDg0LCJleHAiOjE3MjA4MDYxNjYsImF1dGhvcml0aWVzIjoiQUdFTlQiLCJqdGkiOiJkMDM5ZWVjZS03OTNjLTQwMWUtOTQzMS1iYjU4MjIwNGE2M2QiLCJjbGllbnRfaWQiOiIiLCJzY29wZSI6W119.HasiRiPAGEp-E-RpsLNhjmFrTLnbdCU18oAh2b5wmMSpIoxF83roUPGag8HSvDr4ahaiscVodZL-MYdmqYIQvj1YFGg-TEvyi8FZvlZtM2jB06Q5hBOZglHbvwhCi__p6yk3ZvU1wqdWSTu7MHdgQxhIso1otpsrm9A0h-kGHCQ}} # Lembrar de criar as credenciais no Secrets
        run: |
          curl -sSL 'https://download.sourceclear.com/ci.sh' | bash -s – scan --update-advisor --allow-dirty

  Veracode_UploadAndScan:
    runs-on: ubuntu-latest
    needs: Package
    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: pacoteVeracode
      - name: UploadAndScan
        uses: veracode/veracode-uploadandscan-action@master # Faz a analise da Veracode
        env:
          VeracodeID: ${{ secrets.VeracodeID }} # Lembrar de criar as credenciais no Secrets
          VeracodeKey: ${{ secrets.VeracodeKey }}
          AppName: Github Actions - ${{ github.repository }}
        with:
          vid: '$VeracodeID'
          vkey: '$VeracodeKey'
          criticality: 'VeryHigh'
          appname: '$AppName'
          createsandbox: true
          filepath: 'veracode.zip'
          deleteIncompleteScan: false
          version: ${{ github.run_id }}

  Veracode_PipelineScan:
    runs-on: ubuntu-latest
    needs: Package
    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: pacoteVeracode
      - name: Veracode Pipeline Scan
        env:
          VID: ${{922f83a8e13e5fa18837e673669b9351}} # Lembrar de criar as credenciais no Secrets
          VKEY: ${{2199d1106eb946f427bd9af383daf3511b4cfb516d02f4e097cc6654e9018f6c0b0b7f50ede3d0010d43053106cffbb695f10c80d5c9ce8b139db1af64740813}}
          CaminhoArquivo: './veracode.zip'
        run: |
          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar -vid $VID -vkey $VKEY -f $CaminhoArquivo --issue_details true
