name: Veracode_Basic
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Empacotamento dos arquivos
        uses: thedoctor0/zip-release@master
        with:
          filename: 'veracode.zip'
          path: .
      - name: Publicando Artefato
        uses: actions/upload-artifact@v2
        with:
          name: pacoteVeracode
          path: veracode.zip

  Veracode_UploadAndScan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: pacoteVeracode
      - name: UploadAndScan
        uses: veracode/veracode-uploadandscan-action@master # Faz a analise da Veracode
        env:
          VeracodeID: ${{922f83a8e13e5fa18837e673669b9351}} # Lembrar de criar as credenciais no Secrets
          VeracodeKey: ${{2199d1106eb946f427bd9af383daf3511b4cfb516d02f4e097cc6654e9018f6c0b0b7f50ede3d0010d43053106cffbb695f10c80d5c9ce8b139db1af64740813}}
          AppName: Github Actions - ${{ github.repository }}
        with:
          vid: '$VeracodeID'
          vkey: '$VeracodeKey'
          criticality: 'VeryHigh'
          appname: '$AppName'
          createsandbox: true
          filepath: 'veracode.zip'
          deleteIncompleteScan: false
          version: ${{ github.run_id }}
